#!/bin/bash

set -e

remove() {

	# Restore ofono configuration
	if [ -e "/usr/lib/ofono-config-ril-binder/ril_subscription.conf.orig" ]; then
		rm -f "/etc/ofono/ril_subscription.conf"

		dpkg-divert \
			--rename \
			--package ofono-config-ril-binder \
			--divert "/usr/lib/ofono-config-ril-binder/ril_subscription.conf.orig" \
			--remove "/etc/ofono/ril_subscription.conf"
	fi

}

#DEBHELPER#

case $1 in
	"remove")
		remove
		;;
esac
